name: test
on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
     
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Test
        run: make test
